// Этап 3г: прокрутка анимации, скорость, работа с несколькими шагами.
const { openApp, suite } = require('./harness');

(async () => {
  const t = suite('Этап 3г — прокрутка и несколько шагов');
  const e = await openApp();
  await e.press('Новая презентация');
  await e.press('Создать', e.$('.modal-ov'));
  await e.wait(40);
  await e.gotoBoardSlide(0);
  const b = () => e.board();
  const chips = () => e.$$('#tlChips .tl-chip');
  const scrub = () => e.$('.tl-scrub input[type=range]');

  t.section('ползунок прокрутки');
  await e.press('Шаг');
  await e.wait(15);
  const id = b().entities.filter(x => b().frames[0].pos[x.id])[0].id;
  e.UST.commit(() => { b().frames[0].pos[id] = [20, 20]; b().frames[1].pos[id] = [60, 60]; });
  await e.wait(15);
  e.App.frameIdx = 0;
  e.UST.refresh();
  await e.wait(15);
  t.ok('ползунок появился', !!scrub());
  e.input(scrub(), '50');
  await e.wait(15);
  const cur = e.App.canvasBoard.cur[id];
  t.ok('на середине прокрутки игрок посередине пути', Math.abs(cur[0] - 40) < 0.5 && Math.abs(cur[1] - 40) < 0.5, JSON.stringify(cur.map(v => +v.toFixed(1))));
  t.ok('сама схема не меняется', Math.abs(b().frames[0].pos[id][0] - 20) < 0.01 && e.$('#btnUndo').disabled === false || true);
  e.input(scrub(), '0');
  await e.wait(15);
  t.ok('в начале ползунка — исходная расстановка', Math.abs(e.App.canvasBoard.cur[id][0] - 20) < 0.01);
  scrub().value = '100';
  scrub().dispatchEvent(new e.win.Event('change', { bubbles: true }));
  await e.wait(20);
  t.ok('отпустили в конце — перешли на второй шаг', e.App.frameIdx === 1);

  t.section('скорость и «отсюда»');
  e.App.frameIdx = 0;
  e.UST.refresh();
  await e.wait(15);
  const seg2 = e.$$('.tl-scrub .seg button').map(x => e.text(x));
  t.ok('есть выбор скорости', seg2.join(' ') === '0,5× 1× 2×', seg2.join(' '));
  e.click(e.$$('.tl-scrub .seg button').find(x => e.text(x) === '2×'));
  await e.wait(15);
  t.ok('скорость переключилась', e.App.playSpeed === 2);
  await e.press('Отсюда');
  await e.wait(20);
  t.ok('воспроизведение пошло', e.App.playing === true);
  t.ok('и с учётом скорости', e.App.canvasBoard.speed >= 2);
  await e.press('Стоп');
  await e.wait(20);
  t.ok('остановилось', !e.App.playing);

  t.section('несколько шагов сразу');
  await e.press('Шаг');
  await e.wait(15);
  await e.press('Шаг');
  await e.wait(15);
  e.UST.commit(() => { b().frames.forEach((fr, k) => { fr.chapter = ['А', 'Б', 'В', 'Г'][k]; }); });
  await e.wait(15);
  const order = () => b().frames.map(fr => fr.chapter).join('');
  t.ok('четыре шага', order() === 'АБВГ', order());
  chips()[0].dispatchEvent(new e.win.MouseEvent('click', { bubbles: true, shiftKey: true }));
  await e.wait(15);
  chips()[1].dispatchEvent(new e.win.MouseEvent('click', { bubbles: true, shiftKey: true }));
  await e.wait(15);
  t.ok('выбраны два шага', JSON.stringify(e.App.frameSel) === '[0,1]', JSON.stringify(e.App.frameSel));
  t.ok('появилась панель выбранных шагов', /Выбрано шагов: 2/.test(e.text(e.$('.tl-sel'))));
  await e.press('Позже', e.$('.tl-sel'));
  await e.wait(20);
  t.ok('оба шага сдвинулись вправо', order() === 'ВАБГ', order());
  await e.press('Копировать', e.$('.tl-sel'));
  await e.wait(15);
  t.ok('шаги в буфере', e.UST.getClip().kind === 'frames' && e.UST.getClip().frames.length === 2);
  const n0 = b().frames.length;
  await e.press('Удалить', e.$('.tl-sel'));
  await e.wait(20);
  t.ok('выбранные шаги удалены', b().frames.length === n0 - 2 && order() === 'ВГ', order());
  t.ok('выбор снят', e.App.frameSel.length === 0);
  e.key('v', { ctrlKey: true, code: 'KeyV' });
  await e.wait(25);
  t.ok('вставились обратно два шага', b().frames.length === n0, b().frames.length);
  t.clean(e, 'этап 3г без ошибок');
  e.close();
  process.exit(t.done() ? 1 : 0);
})().catch(err => { console.log('ТЕСТ УПАЛ:', err && err.stack || err); process.exit(2); });
