// Этап 6б: свои типы стрелок и свои цвета.
const { openApp, suite } = require('./harness');

(async () => {
  const t = suite('Этап 6б — свои стрелки и цвета');
  const e = await openApp({ idb: true });
  const UST = e.UST;
  await e.press('Открыть пример «Маятник»');
  await e.wait(50);
  await e.gotoBoardSlide(0);

  t.section('свой тип стрелки');
  t.ok('привычные типы на месте', !!UST.arrowPresets().pass && !!UST.arrowPresets().run);
  const two = e.board().entities.filter(x => x.kind === 'ours').slice(0, 2).map(x => x.id);
  e.App.frameIdx = 1;
  const f = () => e.frame();
  f().arrows.push({ id: 'my1', kind: 'line', from: { e: two[0] }, to: { e: two[1] }, style: 'dotted', color: '#12ff34', width: 5.5, head: true, bend: 40, lob: true });
  e.App.sel = { t: 'arrow', i: f().arrows.length - 1 };
  e.UST.refresh(['canvas', 'insp']);
  await e.wait(30);
  const insp = () => e.$('#edInsp') || e.doc.body;
  t.ok('в свойствах стрелки есть кнопка сохранения типа', !!e.button('Сохранить как свой тип', insp()));
  await e.press('Сохранить как свой тип', insp());
  await e.wait(30);
  const ask = e.$$('.modal-ov').pop();
  t.ok('спрашиваем название', /Свой тип стрелки/.test(e.text(ask)));
  t.ok('и спрашиваем про мяч', /Мяч идёт по этой стрелке/.test(e.text(ask)));
  e.input(e.$('input.inp', ask), 'Заброс за спину');
  await e.press('Сохранить', ask);
  await e.wait(40);
  const mine = (UST.Prefs.arrows || [])[0];
  t.ok('тип сохранён', !!mine && mine.name === 'Заброс за спину', JSON.stringify(mine && mine.name));
  t.ok('запомнили вид линии', mine.a.style === 'dotted' && mine.a.color === '#12ff34' && mine.a.width === 5.5 && mine.a.lob === true, JSON.stringify(mine.a));
  t.ok('запомнили изгиб', mine.a.bend === 40);
  t.ok('это не стрелка перемещения', mine.move === false && mine.ball === true);
  t.ok('тип появился в общем списке', UST.arrowPresets()[mine.id].name === 'Заброс за спину' && UST.arrowPresets()[mine.id].custom === true);
  await e.wait(220);
  const saved = await UST.Store.get('ustanovka-prefs');
  t.ok('тип записан на устройстве', /Заброс за спину/.test(String(saved)));

  t.section('свой тип в работе');
  const other = f().arrows.find(a => a.id !== 'my1') || null;
  if (!other) f().arrows.push({ id: 'my2', kind: 'line', from: { e: two[1] }, to: { e: two[0] }, style: 'solid', color: 'run', width: 2, head: true, bend: 0 });
  const idx = f().arrows.findIndex(a => a.id !== 'my1');
  e.App.sel = { t: 'arrow', i: idx };
  e.UST.refresh(['insp']);
  await e.wait(30);
  const typeBtn = e.$$('#edInsp .sw.tk').find(b => e.text(b) === 'Заброс за спину');
  t.ok('свой тип виден в свойствах стрелки', !!typeBtn && typeBtn.classList.contains('mine'));
  e.click(typeBtn);
  await e.wait(30);
  const got = e.frame().arrows[idx];
  t.ok('нажатие применяет мой вид', got.style === 'dotted' && got.color === '#12ff34' && Math.abs(got.width - 5.5) < 0.01, JSON.stringify({ s: got.style, c: got.color, w: got.width }));

  t.section('свой тип в панели стрелок');
  e.App.tool = { m: 'arrow', preset: 'pass' };
  e.UST.refresh(['tools']);
  await e.wait(30);
  const toolBtn = e.$$('.tool-sub .sw.tk').find(b => e.text(b) === 'Заброс за спину');
  t.ok('свой тип есть в панели инструментов', !!toolBtn);
  e.click(toolBtn);
  await e.wait(20);
  t.ok('его можно выбрать', e.App.tool.preset === mine.id, e.App.tool.preset);
  const before = e.frame().arrows.length;
  await e.tap(null, [30, 30]);
  await e.tap(null, [70, 60]);
  await e.wait(30);
  const made = e.frame().arrows[e.frame().arrows.length - 1];
  t.ok('новая стрелка нарисована моим типом', e.frame().arrows.length === before + 1 && made.style === 'dotted' && made.color === '#12ff34', JSON.stringify({ n: e.frame().arrows.length - before, s: made && made.style }));
  UST.removeArrowType(mine.id);
  await e.wait(20);
  t.ok('тип можно убрать', !UST.arrowPresets()[mine.id] && (UST.Prefs.arrows || []).length === 0);
  t.ok('инструмент вернулся к обычному', e.App.tool.preset === 'run', e.App.tool.preset);

  t.section('мои цвета');
  t.ok('новый цвет добавляется', UST.addPaletteColor('#123456') === true && UST.Prefs.palette[0] === '#123456');
  t.ok('дважды один цвет не добавляем', UST.addPaletteColor('#123456') === false && UST.Prefs.palette.length === 1);
  t.ok('и цвет из стандартных тоже', UST.addPaletteColor('#ffffff') === false, JSON.stringify(UST.Prefs.palette));
  t.ok('мусор не принимаем', UST.addPaletteColor('красный') === false && UST.addPaletteColor('') === false);
  e.App.sel = null;
  e.UST.refresh(['insp']);
  await e.press('Настройки');
  await e.wait(30);
  const dlg = () => e.$$('.modal-ov').pop();
  await e.press('Команды', dlg());
  await e.wait(30);
  const swatches = e.$$('.sw[data-v="#123456"]', dlg());
  t.ok('мой цвет виден в выборе цвета', swatches.length > 0, swatches.length);
  t.ok('и кнопка «плюс» рядом есть', e.$$('.sw-add', dlg()).length > 0);
  e.click(swatches[0]);
  await e.wait(30);
  t.ok('по нему можно покрасить', e.App.project.settings.colors.ours === '#123456', e.App.project.settings.colors.ours);
  await e.press('Оформление', dlg());
  await e.wait(30);
  t.ok('в оформлении есть раздел моих цветов', /Мои цвета/.test(e.text(dlg())));
  const rm = e.$$('.exp-card .sw[data-v="#123456"]', dlg()).pop();
  t.ok('мой цвет показан отдельным списком', !!rm);
  e.click(rm);
  await e.wait(30);
  t.ok('и убирается нажатием', (UST.Prefs.palette || []).indexOf('#123456') < 0, JSON.stringify(UST.Prefs.palette));
  const cl = e.button('Закрыть', dlg());
  if (cl) e.click(cl);
  await e.wait(20);
  t.clean(e, 'этап 6б без ошибок');
  e.close();
  process.exit(t.done() ? 1 : 0);
})().catch(err => { console.log('ТЕСТ УПАЛ:', err && err.stack || err); process.exit(2); });
