// Этап 6в: свои расстановки, своё оформление, эмблема и название команды.
const { openApp, suite } = require('./harness');

const PNG = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==';

(async () => {
  const t = suite('Этап 6в — расстановки, оформление, эмблема');
  const e = await openApp({ idb: true });
  const TE = e.TE, UST = e.UST;
  await e.press('Открыть пример «Маятник»');
  await e.wait(50);
  await e.gotoBoardSlide(0);

  t.section('снимок расстановки с поля');
  const spots = UST.boardSpots('ours');
  t.ok('игроки собраны с поля', spots.length >= 6, spots.length);
  t.ok('вратарь идёт первым', spots[0].gk === true, JSON.stringify(spots[0]));
  t.ok('дальше — от защиты к атаке', spots.slice(1).every((s, i, a) => i === 0 || a[i - 1].y >= s.y), JSON.stringify(spots.map(s => s.y)));
  t.ok('у каждого есть место и подпись', spots.every(s => s.x >= 0 && s.x <= 100 && typeof s.label === 'string'));
  const mir = UST.mirrorSpots(spots);
  t.ok('зеркало переворачивает поле', Math.abs(mir[0].x - (100 - spots[0].x)) < 0.11 && Math.abs(mir[0].y - (100 - spots[0].y)) < 0.11, JSON.stringify(mir[0]));

  t.section('сохранение своей расстановки');
  await e.press('Расстановка');
  await e.wait(30);
  const dlg = () => e.$$('.modal-ov').pop();
  t.ok('окно расстановки открылось', /Расстановка/.test(e.text(dlg())));
  await e.press('Запомнить расстановку с поля', dlg());
  await e.wait(30);
  e.input(e.$('input.inp', dlg()), 'Наш квадрат');
  await e.press('Сохранить', dlg());
  await e.wait(40);
  const mine = (UST.Prefs.formations || [])[0];
  t.ok('расстановка сохранена', !!mine && mine.name === 'Наш квадрат', JSON.stringify(mine && mine.name));
  t.ok('в ней столько же игроков', mine.n === spots.length, mine.n + ' из ' + spots.length);
  t.ok('и запомнено, за кого она', mine.team === 'ours');
  t.ok('в окне расстановки она появилась', !!e.button('Наш квадрат', dlg()));

  t.section('применение своей расстановки');
  const b = e.board();
  const before = JSON.stringify(e.frame().pos);
  e.frame().pos[b.entities.filter(x => x.kind === 'ours')[1].id] = [5, 5];
  await e.press('Наш квадрат', dlg());
  await e.wait(50);
  t.ok('окно закрылось и игроки встали как надо', JSON.stringify(e.frame().pos) === before, 'совпало: ' + (JSON.stringify(e.frame().pos) === before));

  t.section('та же расстановка за соперника');
  await e.press('Расстановка');
  await e.wait(30);
  await e.press('Соперник', dlg());
  await e.wait(20);
  await e.press('Наш квадрат', dlg());
  await e.wait(50);
  const opp = e.board().entities.filter(x => x.kind === 'opp');
  t.ok('соперник расставлен', opp.length >= spots.length, opp.length);
  const oppPos = opp.map(x => e.frame().pos[x.id]).filter(Boolean);
  t.ok('и стоит зеркально — на своей половине', oppPos.filter(p => p[1] < 50).length > oppPos.filter(p => p[1] > 50).length, JSON.stringify(oppPos.map(p => Math.round(p[1]))));

  t.section('название команды и эмблема');
  await e.press('Настройки');
  await e.wait(30);
  await e.press('Оформление', dlg());
  await e.wait(30);
  t.ok('есть раздел команды и эмблемы', /Команда и эмблема/.test(e.text(dlg())));
  const teamIn = e.$$('input.inp', dlg())[0];
  e.input(teamIn, 'ФК Молния');
  await e.wait(30);
  t.ok('название команды сохранилось', e.App.project.settings.brand.team === 'ФК Молния', e.App.project.settings.brand.team);
  e.UST.commit(p => { p.settings.brand.logo = PNG; }, { parts: ['main'] });
  await e.wait(20);
  const withLogo = TE.normalizeProject(JSON.parse(JSON.stringify(e.App.project)));
  t.ok('эмблема прошла проверку', withLogo.settings.brand.logo === PNG);
  t.ok('чужая ссылка вместо картинки не принимается', TE.normalizeProject({ settings: { brand: { logo: 'https://site/logo.png' } }, slides: [] }).settings.brand.logo === '');
  const cl0 = e.button('Закрыть', dlg());
  if (cl0) e.click(cl0);
  await e.wait(20);
  e.App.project.slides[0].layout = 'title';
  await e.press('Показ');
  await e.wait(60);
  t.ok('эмблема видна в шапке показа', !!e.$('.ed-preview .te-logo .te-badge'), e.$('.ed-preview .te-logo').innerHTML.slice(0, 40));
  const brandEl = e.$('.ed-preview .te-slide.on .te-brand') || e.$('.ed-preview .te-brand');
  t.ok('на титульном слайде видны эмблема и команда', !!brandEl && /ФК Молния/.test(e.text(brandEl)) && !!e.$('img', brandEl), e.text(brandEl));
  await e.press('Закрыть', e.$('.ed-preview'));
  await e.wait(30);

  t.section('своё оформление');
  e.UST.commit(p => { p.settings.look.accent = '#00ccff'; p.settings.colors.ours = '#112233'; p.settings.pitch.grass = '#101010'; }, { parts: [] });
  await e.press('Настройки');
  await e.wait(30);
  await e.press('Оформление', dlg());
  await e.wait(30);
  await e.press('Сохранить текущее оформление', dlg());
  await e.wait(30);
  e.input(e.$('input.inp', dlg()), 'Наши цвета');
  await e.press('Сохранить', dlg());
  await e.wait(40);
  const th = (UST.Prefs.themes || [])[0];
  t.ok('оформление сохранено', !!th && th.name === 'Наши цвета', JSON.stringify(th && th.name));
  t.ok('в нём цвета и шрифты', th.look.accent === '#00ccff' && th.colors.ours === '#112233' && th.pitch.grass === '#101010', JSON.stringify({ a: th.look.accent, o: th.colors.ours, g: th.pitch.grass }));
  t.ok('геометрия поля в оформление не попала', th.pitch.ratio === undefined && th.formats === undefined);
  e.UST.commit(p => { p.settings.look.accent = '#ff7a00'; p.settings.colors.ours = '#2456c7'; p.settings.pitch.grass = '#3a8a55'; }, { parts: [] });
  UST.applyTheme(th);
  await e.wait(30);
  const st = e.App.project.settings;
  t.ok('оформление применяется целиком', st.look.accent === '#00ccff' && st.colors.ours === '#112233' && st.pitch.grass === '#101010', JSON.stringify({ a: st.look.accent, o: st.colors.ours, g: st.pitch.grass }));
  await e.wait(230);
  const saved = await UST.Store.get('ustanovka-prefs');
  t.ok('всё моё записано на устройстве', /Наши цвета/.test(String(saved)) && /Наш квадрат/.test(String(saved)));
  UST.removeTheme(th.id);
  UST.removeFormation(mine.id);
  await e.wait(20);
  t.ok('своё можно убирать', (UST.Prefs.themes || []).length === 0 && (UST.Prefs.formations || []).length === 0);
  const cl = e.button('Закрыть', dlg());
  if (cl) e.click(cl);
  await e.wait(20);
  t.clean(e, 'этап 6в без ошибок');
  e.close();
  process.exit(t.done() ? 1 : 0);
})().catch(err => { console.log('ТЕСТ УПАЛ:', err && err.stack || err); process.exit(2); });
